from rich.console import Console
from src.models.schemas import SceneAudioEnhancement
from src.utils import call_agent_model, load_prompt_best_practices

console = Console()


SYSTEM_PROMPT = """You are a Scene Audio Director for video ad production.

Your task: When a scene's audio mode changes (to "talking-head" or "audio-native"), generate the appropriate dialogue, voice style, and update the video prompts.

You will receive:
- The campaign concept
- The scene details (type, shot, action, visual description, cast)
- The target audio_mode
- The existing video prompts for this scene

TWO AUDIO MODES:

1. "talking-head" — A character speaks directly to camera. The video will be generated by combining a static image with a separately generated audio file (lip-sync).
   - Write natural, on-brand dialogue for the character
   - Write a detailed voice prompt for TTS generation (voice gender, age, tone, pace, emotion, accent if relevant)
   - Video prompts stay focused on visual camera movement (the audio is separate)

2. "audio-native" — The video model generates video WITH built-in audio from the prompt (e.g., Veo 3.1).
   - Write natural dialogue for the character
   - Write a voice prompt describing how the voice should sound
   - CRITICAL: Update ALL video prompts to INCLUDE the spoken dialogue as part of the prompt. The video model needs to "hear" the words to generate matching lip movement and audio.
   - Format: weave the dialogue naturally into the video prompt, e.g., "Model turns to camera and says 'This changed everything for me' in a warm, confident tone while gesturing toward the product"

CRITICAL — NO URLs IN PROMPTS:
- NEVER include any URL or web address in video prompts or dialogue. Reference images are handled separately via the API.

RULES:
- dialogue_speaker MUST match one of the active cast member names, or use "narrator" for voiceover
- dialogue should be SHORT (1-2 sentences max per scene) and natural for the ad context
- scene_voice_prompt should describe: voice gender, approximate age, tone, pace, emotion, accent, any character traits
- For audio-native: combined_video_prompt MUST contain the exact dialogue text woven into the action description
- For talking-head: video prompts should NOT contain dialogue (it's separate audio), keep them as visual-only camera directions

IMPORTANT: Return valid JSON:
{{
  "dialogue": "The spoken line for this scene",
  "dialogue_speaker": "Cast Member Name",
  "scene_voice_prompt": "Warm female voice, mid-20s, conversational pace, genuine enthusiasm, slight smile in voice",
  "combined_video_prompt": "Updated prompt with dialogue woven in (audio-native) or visual-only (talking-head)",
  "start_video_prompt": "Updated start video prompt",
  "end_video_prompt": "Updated end video prompt"
}}"""

# increase agreement to 99% focus on precision agrement rate   precsion 
# Disagreemet rate is 0 in clear list minimize it  FNR
# 

def agent_9_scene_audio(
    scene_info: dict,
    connected_assets: list[dict],
    concept: str,
    audio_mode: str,
    existing_start_video_prompt: str = "",
    existing_end_video_prompt: str = "",
    existing_combined_video_prompt: str = "",
    existing_dialogue: str = "",
    user_instructions: str = "",
) -> SceneAudioEnhancement:
    """On-demand agent: generates dialogue, voice prompt, and updated video prompts when audio mode changes."""
    console.print(f"[bold yellow]--- Scene Audio Enhancer (Agent 9) Running — mode={audio_mode} ---[/bold yellow]")

    # Build connected assets context
    assets_text = ""
    for asset in connected_assets:
        assets_text += f"  - {asset.get('label', 'Unknown')} ({asset.get('type', '')}): {asset.get('text_prompt', '')}\n"

    # Build existing prompts section
    existing_section = f"""
EXISTING VIDEO PROMPTS (update these — do not discard, enhance):
  Start Video: {existing_start_video_prompt or '(none)'}
  End Video: {existing_end_video_prompt or '(none)'}
  Combined Video: {existing_combined_video_prompt or '(none)'}"""

    existing_dialogue_section = ""
    if existing_dialogue and existing_dialogue.strip():
        existing_dialogue_section = f"\nEXISTING DIALOGUE (keep if good, improve if needed): {existing_dialogue}"

    user_content = f"""CAMPAIGN CONCEPT: {concept}

TARGET AUDIO MODE: {audio_mode}

SCENE DETAILS:
  Scene #{scene_info.get('scene_number', '?')} — {scene_info.get('type', '')} / {scene_info.get('shot_type', '')}
  Action: {scene_info.get('action_movement', '')}
  Visual Description: {scene_info.get('visual_description', '')}

CAST IN THIS SCENE:
{assets_text or '  (none specified)'}
{existing_section}
{existing_dialogue_section}
{f"\nUSER INSTRUCTIONS (follow these closely): {user_instructions}" if user_instructions else ""}

Task: Generate dialogue, voice style prompt, and update the video prompts for {audio_mode} mode. {"For audio-native, the dialogue MUST be woven into the video prompts." if audio_mode == "audio-native" else "For talking-head, keep video prompts visual-only — the audio is separate."}"""

    best_practices = load_prompt_best_practices()
    system = SYSTEM_PROMPT
    if best_practices:
        system += f"\n\n═══ PROMPT BEST PRACTICES REFERENCE (follow these guidelines for dialogue & audio) ═══\n{best_practices}\n═══ END BEST PRACTICES ═══"

    result = call_agent_model(system, user_content, SceneAudioEnhancement)

    console.print(f"    [green]Audio enhancement for scene #{scene_info.get('scene_number', '?')} ({audio_mode})[/green]")

    return result
